# Generated by Django 2.2.26 on 2022-12-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='user',
            name='privacy_policy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('owner', 'owner'), ('end_user', 'end_user')], default='owner', max_length=8),
        ),
    ]
